apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: curl-deployment
  name: curl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: curl-deployment
    spec:
      containers:
      - image: soroushmehraban2022/new-alpine:1.0
        name: new-alpine
        command: ["/bin/sleep"]
        args: ["infinite"]
        resources: {}
status: {}
